### ISSUE TITLE
Bug in program view after pressing "Начать" button

### ISSUE THREAD

**Issue by ASinyukhin** [banarum/thesis-medapp#1]
В случае, если Тип программы был изменён без сохранения, после нажатия "Начать" и последующей прошивки всплывает список с типами программ.
![image](https://user-images.githubusercontent.com/44834475/82919151-efb79f80-9f75-11ea-9f9b-da7a7d99fe09.png)
![image](https://user-images.githubusercontent.com/44834475/82919196-00681580-9f76-11ea-9461-f02e22f446d9.png)
![image](https://user-images.githubusercontent.com/44834475/82919211-05c56000-9f76-11ea-89b0-7be121439eb3.png)

**Comment by banarum** [comment]
Done. I updated state strategy for this fragment to SkipStrategy
