### ISSUE TITLE
Implement menu for operations with treatment programs

### ISSUE THREAD

**Issue by ASinyukhin** [banarum/thesis-medapp#2]
По долгому нажатию должно появляться меню со следующими операциями с программой лечения:
* удалить.
* клонировать (копировать под новым именем);
* редактировать
Рекомендуется реализовать либо в виде всплывающего меню, либо в виде кнопок с операцими, появляющихся сверху в StatusBar.
Во избежании случайного удаления программы лечения, должнен быть сделан диалог подтверждения удаления **(!)**
Приоритет: **высокий**

**Comment by banarum** [comment]
Done
