### ISSUE TITLE
Add pause duration parameter

### ISSUE THREAD

**Issue by ASinyukhin** [banarum/thesis-medapp#4]
В текущей версии моб. приложения параметр паузы между сериями импульсов отсутствует (он устанавливается равным длительности серии импульсов).
Необходимо добавить этот параметр в интерфейс создания/редактирования программы лечения.

**Comment by ASinyukhin** [comment]
Для лучшего понимания прикладываю схему
![Impulses](https://user-images.githubusercontent.com/44834475/83024396-9bbcc180-a02e-11ea-8f0b-0772d7bb1e91.png)

**Comment by banarum** [comment]
Done
