### ISSUE TITLE
Make battery charge indicator permanent and add percentage

### ISSUE THREAD

**Issue by ASinyukhin** [banarum/thesis-medapp#5]
В идеальном случае батарейка в StatusBar должна быть всегда вне зависимости от подключения. При отсутствии коннекта с устройством отображать пустую батарейку с '?' знаком внутри. При наличии коннекта отображать внутри заряд батареи в процентах, поверх графически наприсованного уровня (как это сделано в большинстве смартфонов).
Приоритет: **высокий**

**Comment by banarum** [comment]
Done
