### ISSUE TITLE
Remove unnecessary input elements from treatment program view

### ISSUE THREAD

**Issue by ASinyukhin** [banarum/thesis-medapp#7]
Задача имеет невысокий приоритет, но нужно сделать скрин с программой лечения минималистичным, убрав и без того не работающие контролы:
![NewProgramView](https://user-images.githubusercontent.com/44834475/82926987-47f39f00-9f80-11ea-8fb7-f8bfaf0c8676.jpg)

**Comment by ASinyukhin** [comment]
UPD: шрифт в статусе канала и двуполярном режиме такой же, как в "форме импульсов".

**Comment by banarum** [comment]
Done
